### ISSUE TITLE
Not working (yet?) with the DallasTemperature library

### ISSUE THREAD

**Issue by urish** [bonnyr/wokwi-ds1820-custom-chip#7] opened 2022-12-14 22:22 UTC
I'm trying to use the chip with the [DallasTemperature](https://github.com/milesburton/Arduino-Temperature-Control-Library) library, but it doesn't seem to work: https://wokwi.com/projects/351023152576332372

when connecting a logic analyzer to the DQ pin, and use PulseView's 1-Wire Network Layer analyzer, it shows some errors:

![image](https://user-images.githubusercontent.com/892318/207727617-9275a272-763a-4900-975f-e742303ad271.png)

**Comment by bonnyr** [comment] 2022-12-14 23:15
> I'm trying to use the chip with the [DallasTemperature](https://github.com/milesburton/Arduino-Temperature-Control-Library) library, but it doesn't seem to work: https://wokwi.com/projects/351023152576332372
> 
> when connecting a logic analyzer to the DQ pin, and use PulseView's 1-Wire Network Layer analyzer, it shows some errors:
> 
> ![image](https://user-images.githubusercontent.com/892318/207727617-9275a272-763a-4900-975f-e742303ad271.png)

@urish - thanks for the feedback

The test program in the repo shows usage of the OneWire library and the sequence of commands that was used to test.
The repo has a capture that shows the test run and appears to be working as intended

I'll check your test use case ...

**Comment by bonnyr** [comment] 2022-12-14 23:23
@urish - one issue could be that the serial number is not of a Dallas DS18B20 but rather a sample valid OneWire address

**Comment by bonnyr** [comment] 2022-12-15 00:54
@urish  ok, some update (still not sure who's wrong here...):

I noticed a couple of things:
1. in your capture, and the linked program, the library starts quickly. It seems that PulseView requires that some time elapses before the reset pulse is considered valid (although the software does not care and handles the signals correctly). When I added a delay of 1ms before `sensors.begin()`, the captures started showing up correctly.
2. It appears that after requesting conversion there is a pulse on the bus immediately. I'm still not sure what that is.

![image](https://user-images.githubusercontent.com/2648551/207745600-3b967cc2-8655-4c63-8da5-32dfaf0992e7.png)

<img width="435" alt="image" src="https://user-images.githubusercontent.com/2648551/207745720-6e9fcec5-2661-4b6c-a817-ecb1ec29059a.png">

The debug code shows this :

[chip-ds18b20] ow_ctx: resetting state from ST_RESET_INIT
[chip-ds18b20] 38801062 sm_push_event< sm_read_byte (ctx: 0x134c0) next state=> ST_READ_RUNNING(0)
[chip-ds18b20] on_master_write_done_pin_chg: ctx->state after callback 5 (was set by us to 0)
[chip-ds18b20] 38801062 sm_push_event< sm_sig (ctx: 0x13470) next state=> ST_RESET_INIT(0)
[chip-ds18b20] **38811375** sm_push_event> (38811) sm_sig (ctx:0x13470) ST_RESET_INIT[EV_PIN_CHG]: on_reset_init_pin_chg( 0 ) -> 0x8
[chip-ds18b20] on_reset_init_pin_chg - ctx: 0x13470
[chip-ds18b20] 38811375 sm_push_event< sm_sig (ctx: 0x13470) next state=> ST_RESET_WAIT_RELEASE(1)
[chip-ds18b20] **38813937** sm_push_event> **--->(2)<---** sm_sig (ctx:0x13470) ST_RESET_WAIT_RELEASE[EV_PIN_CHG]: on_reset_wait_release_pin_chg( 1 ) -> 0x9
[chip-ds18b20] 38813937 sm_push_event< sm_sig (ctx: 0x13470) next state=> ST_RESET_WAIT_PRESENCE(2)



I am not sure why the master issues a reset pulse so quickly after the command but does not follow it up with another command.
I am also not sure why the master changes the bus back to 1.

I don't think the custom chip is strictly incorrect here.

However, the chip could benefit from some protection logic  - among the todo's I still have to complete.

For completeness, this is the test code I used:
```C
#include <OneWire.h>
#include <DallasTemperature.h>

OneWire oneWire(10);
DallasTemperature sensor(&oneWire);

void setup(void) {
  Serial.begin(115200);
  pinMode(2, OUTPUT);
  pinMode(3, OUTPUT);
  digitalWrite(2, HIGH);

  delay(2);
  sensor.begin();
  delay(20);
}

void loop(void) {
  sensor.requestTemperatures();
  Serial.print("Temperature is: ");
  delay(10);
  Serial.println(sensor.getTempCByIndex(0));
  delay(1000);
}
```
[wokwi-logic.7.vcd.txt](https://github.com/bonnyr/wokwi-ds1820-custom-chip/files/10235149/wokwi-logic.7.vcd.txt)

**Comment by bonnyr** [comment] 2022-12-21 04:02
closing this issue due to misbehaviour of DallasTemperature as well as making the chip more defensive

**Closed as completed by bonnyr** 2022-12-21 04:02 UTC

**Comment by urish** [comment] 2022-12-21 07:49
Thanks!
